// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package order

import (
	"edtech.id/internal/cart/repository"
	cart2 "edtech.id/internal/cart/usecase"
	"edtech.id/internal/discount/repository"
	discount2 "edtech.id/internal/discount/usecase"
	"edtech.id/internal/order/delivery/http"
	order2 "edtech.id/internal/order/repository"
	order3 "edtech.id/internal/order/usecase"
	"edtech.id/internal/order_detail/repository"
	order_detail2 "edtech.id/internal/order_detail/usecase"
	"edtech.id/internal/payment/usecase"
	"edtech.id/internal/product/repository"
	product2 "edtech.id/internal/product/usecase"
	"edtech.id/pkg/fileupload/cloudinary"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *order.OrderHandler {
	orderRepository := order2.NewOrderRepository(db)
	cartRepository := cart.NewCartRepository(db)
	cartUsecase := cart2.NewCartUsecase(cartRepository)
	discountRepository := discount.NewDiscountRepository(db)
	discountUsecase := discount2.NewDiscountUsecase(discountRepository)
	productRepository := product.NewProductRepository(db)
	fileUpload := fileupload.NewFileUpload()
	productUseCase := product2.NewProductUseCase(productRepository, fileUpload)
	orderDetailRepository := order_detail.NewOrderDetailRepository(db)
	orderDetailUsecase := order_detail2.NewOrderDetailUsecase(orderDetailRepository)
	paymentUsecase := payment.NewPaymentUsecase()
	orderUsecase := order3.NewOrderUsecase(orderRepository, cartUsecase, discountUsecase, productUseCase, orderDetailUsecase, paymentUsecase)
	orderHandler := order.NewOrderHandler(orderUsecase)
	return orderHandler
}
