// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cart

import (
	"edtech.id/internal/cart/delivery/http"
	"edtech.id/internal/cart/repository"
	cart2 "edtech.id/internal/cart/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *handler.CartHandler {
	cartRepository := cart.NewCartRepository(db)
	cartUsecase := cart2.NewCartUsecase(cartRepository)
	cartHandler := handler.NewCartHandler(cartUsecase)
	return cartHandler
}
