// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package discount

import (
	"edtech.id/internal/discount/delivery/http"
	discount2 "edtech.id/internal/discount/repository"
	discount3 "edtech.id/internal/discount/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *discount.DiscountHandler {
	discountRepository := discount2.NewDiscountRepository(db)
	discountUsecase := discount3.NewDiscountUsecase(discountRepository)
	discountHandler := discount.NewDiscountHandler(discountUsecase)
	return discountHandler
}
