// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package class_room

import (
	"edtech.id/internal/class_room/delivery/http"
	class_room2 "edtech.id/internal/class_room/repository"
	class_room3 "edtech.id/internal/class_room/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *class_room.ClassRoomHandler {
	classRoomRepository := class_room2.NewClassRoomRepository(db)
	classRoomUsecase := class_room3.NewClassRoomUsecase(classRoomRepository)
	classRoomHandler := class_room.NewClassRoomHandler(classRoomUsecase)
	return classRoomHandler
}
