// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product_category

import (
	"edtech.id/internal/product_category/delivery/http"
	product_category2 "edtech.id/internal/product_category/repository"
	product_category3 "edtech.id/internal/product_category/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *product_category.ProductCategoryHandler {
	productCategoryRepository := product_category2.NewProductCategoryRepository(db)
	productCategoryUseCase := product_category3.NewProductCategoryUseCase(productCategoryRepository)
	productCategoryHandler := product_category.NewProductCategoryHandler(productCategoryUseCase)
	return productCategoryHandler
}
