// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admin

import (
	"edtech.id/internal/admin/delivery/http"
	admin2 "edtech.id/internal/admin/repository"
	admin3 "edtech.id/internal/admin/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAdminHandler(db *gorm.DB) *admin.AdminHandler {
	adminRepository := admin2.NewAdminRepository(db)
	adminUseCase := admin3.NewAdminUseCase(adminRepository)
	adminHandler := admin.NewAdminHandler(adminUseCase)
	return adminHandler
}
